module.exports = {
    technologies: {
        'cli': 'Command Line Interface tool',
        css: 'Cascading Style Sheets',
        'node-js': 'Node.js',
        'vagrant': 'Vagrant Docker Provisioner',
        mysql: 'MySQL',
        svn: 'SVN Version Control',
        git: 'Git Version Control',
        bazaar: 'Bazaar Version Control',
        html: 'HTML',
        typescript: 'TypeScript',
        php: 'PHP',
        javascript: 'Javascript',
        internationalization: 'Internationalization',
        'client-interaction': 'Client / Customer Interaction',
        'project-management': 'Project Management',
        'vue-js': 'Vue.js',
        'stakeholder-interaction': 'Stake Holder Interaction',
        'big-data': 'Big Data',
        bash: 'Bash',
        aws: 'Amazon Web Services',
        'ant-design': 'Ant Design',
        'web-scraping': 'Web Scraping',
        'react-native': 'React Native',
        'q-a-a': 'Quality Assurance and Testing',
        'data-aggregation': 'Data Aggregation',
        sass: 'Sass - Stylesheet language',
        'express-js': 'Express',
        docker: 'Docker',
        azure: 'Microsoft Azure',
        nuxt: 'Nuxt.js',
        'scrum-master': 'Scrum Master',
        mentoring: 'Mentoring',
        pwa: 'Progressive Web App',
        qt: 'Qt',
        symfony: 'Symfony',
        ansible: 'Ansible',
        gcp: 'Google Cloud Platform',
        less: 'Less',
        vite: 'Vite',
        flutter: 'Flutter.',
        ats: 'Abstract Syntax Tree',
        transpiler: 'Transpiler',
        redis: 'Redis DB',
        'react-web': 'React Web',
        'ethers-js': 'Ethers.js',
        tui: 'Terminal User Interface',
        documentation: 'Documentation',
        'g-apis': 'Google APIs',
        firebase: 'Firebase',
        'cpp': 'C++',
        'dynamo-db': 'Amazon DynamoDB',
        laravel: 'Laravel',
        cryptography: 'Cryptography',
        electron: 'Electron',
        fintech: 'Financial Technology',
        ocr: 'Optical Character Recognition',
        elasticsearch: 'Elasticsearch',
        wordpress: 'WordPress',
        'chrome-extension': 'Chrome Extension',
        'c-s': 'C# / .NET',
        xml: 'XML',
        qlik: 'Qlik',
        c: 'C Language.',
        'code-igniter': 'CodeIgniter',
        java: 'Java',
        'native-android': 'Native Android',
    },

    badges: {
        entrepreneur: '[![Entrepreneur](https://img.shields.io/badge/Entrepreneur-%237D4698.svg?&style=for-the-badge&logo=entrepreneur&logoColor=green)](https://travis-ci.org/user/repo)',
        'chat-gpt': '![ChatGPT](https://img.shields.io/badge/chatGPT-74aa9c?style=for-the-badge&logo=openai&logoColor=white)',
        'cli': '![CLI](https://img.shields.io/badge/CLI-%234D4D4D.svg?style=for-the-badge&logo=windows-terminal&logoColor=white)',
        css: '![CSS](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white)',
        'node-js': '![Node.js](https://img.shields.io/badge/Node.js-%23339933.svg?&style=for-the-badge&logo=node.js&logoColor=white)',
        'vagrant': '![Vagrant](https://img.shields.io/badge/vagrant-%231563FF.svg?style=for-the-badge&logo=vagrant&logoColor=white)',
        mysql: '![SQL](https://img.shields.io/badge/SQL-%23E34F26.svg?&style=for-the-badge&logo=sql&logoColor=white)',
        // svn: '',
        git: '![Git](https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white)',
        // bazaar: '',
        html: '![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white)',
        typescript: '![TypeScript](https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white)',
        php: '![PHP](https://img.shields.io/badge/php-%23777BB4.svg?style=for-the-badge&logo=php&logoColor=white)',
        javascript: '![JavaScript](https://img.shields.io/badge/JavaScript-%23F7DF1E.svg?&style=for-the-badge&logo=javascript&logoColor=black)',
        // internationalization: '',
        // 'client-interaction': '',
        'project-management': '![Project Management](https://img.shields.io/badge/Project%20Management-%23F7B93E.svg?&style=for-the-badge&logo=product-hunt&logoColor=white)',
        'vue-js': '![Vue.js](https://img.shields.io/badge/vuejs-%2335495e.svg?style=for-the-badge&logo=vuedotjs&logoColor=%234FC08D)',
        // 'stakeholder-interaction': '',
        // 'big-data': '',
        bash: '![Shell Script](https://img.shields.io/badge/shell_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white)',
        aws: '![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=for-the-badge&logo=amazon-aws&logoColor=white)',
        'ant-design': '![Ant-Design](https://img.shields.io/badge/-AntDesign-%230170FE?style=for-the-badge&logo=ant-design&logoColor=white)',
        // 'web-scraping': '',
        'react-native': '![React Native](https://img.shields.io/badge/react_native-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)',
        // 'q-a-a': '',
        // 'data-aggregation': '',
        sass: '![SASS](https://img.shields.io/badge/SASS-hotpink.svg?style=for-the-badge&logo=SASS&logoColor=white)',
        'express-js': '![Express.js](https://img.shields.io/badge/express.js-%23404d59.svg?style=for-the-badge&logo=express&logoColor=%2361DAFB)',
        docker: '![Docker](https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white)',
        azure: '![Azure](https://img.shields.io/badge/azure-%230072C6.svg?style=for-the-badge&logo=microsoftazure&logoColor=white)',
        nuxt: '![Nuxtjs](https://img.shields.io/badge/Nuxt-002E3B?style=for-the-badge&logo=nuxtdotjs&logoColor=#00DC82)',
        // 'scrum-master': '',
        // mentoring: '',
        // pwa: '',
        qt: '![Qt](https://img.shields.io/badge/Qt-%23217346.svg?style=for-the-badge&logo=Qt&logoColor=white)',
        symfony: '![Symfony](https://img.shields.io/badge/symfony-%23000000.svg?style=for-the-badge&logo=symfony&logoColor=white)',
        ansible: '![Ansible](https://img.shields.io/badge/Ansible-%231A1918.svg?&style=for-the-badge&logo=ansible&logoColor=white)',
        gcp: '![GCP](https://img.shields.io/badge/GCP-%234285F4.svg?style=for-the-badge&logo=google-cloud&logoColor=white)',
        less: '![Less](https://img.shields.io/badge/less-2B4C80?style=for-the-badge&logo=less&logoColor=white)',
        vite: '![Vite](https://img.shields.io/badge/vite-%23646CFF.svg?style=for-the-badge&logo=vite&logoColor=white)',
        flutter: '![Flutter](https://img.shields.io/badge/Flutter-%2302569B.svg?style=for-the-badge&logo=Flutter&logoColor=white)',
        // ats: '',
        // transpiler: '',
        redis: '![Redis](https://img.shields.io/badge/redis-%23DD0031.svg?style=for-the-badge&logo=redis&logoColor=white)',
        'react-web': '![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB)',
        // 'ethers-js': '',
        // tui: '',
        // documentation: '',
        // 'g-apis': '',
        firebase: '![Firebase](https://img.shields.io/badge/Firebase-039BE5?style=for-the-badge&logo=Firebase&logoColor=white)',
        'cpp': '![C++](https://img.shields.io/badge/c++-%2300599C.svg?style=for-the-badge&logo=c%2B%2B&logoColor=white)',
        'dynamo-db': '![AmazonDynamoDB](https://img.shields.io/badge/Amazon%20DynamoDB-4053D6?style=for-the-badge&logo=Amazon%20DynamoDB&logoColor=white)',
        laravel: '![Laravel](https://img.shields.io/badge/laravel-%23FF2D20.svg?style=for-the-badge&logo=laravel&logoColor=white)',
        // cryptography: '',
        electron: '![Electron.js](https://img.shields.io/badge/Electron-191970?style=for-the-badge&logo=Electron&logoColor=white)',
        // fintech: '',
        // ocr: '',
        elasticsearch: '![ElasticSearch](https://img.shields.io/badge/-ElasticSearch-005571?style=for-the-badge&logo=elasticsearch)',
        wordpress: '![WordPress](https://img.shields.io/badge/WordPress-%23117AC9.svg?style=for-the-badge&logo=WordPress&logoColor=white)',
        'chrome-extension': '![Google Chrome](https://img.shields.io/badge/Google%20Chrome-4285F4?style=for-the-badge&logo=GoogleChrome&logoColor=white)',
        'c-s': '![C#](https://img.shields.io/badge/c%23-%23239120.svg?style=for-the-badge&logo=csharp&logoColor=white)',
        // xml: '',
        // qlik: '',
        c: '![C](https://img.shields.io/badge/c-%2300599C.svg?style=for-the-badge&logo=c&logoColor=white)',
        'code-igniter': '![Code-Igniter](https://img.shields.io/badge/CodeIgniter-%23EF4223.svg?style=for-the-badge&logo=codeIgniter&logoColor=white)',
        java: '![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white)',
        'native-android': '![Android](https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white)',
    },

    similarResponsibilities: [
        'Software Testing',
        'Bug Fixing',
        'Infrastructure Architect',
        'Assembled great teams (Management based roles)'
    ],

    workHistory: [
        {
            date: '01/2019 - 01/2024',
            site: '<a href="http://www.multithreadlabs.io/" class="site-link" target="_blank">MultithreadLabs.io</a>',
            role: 'I.T Solutions Analyst',
            location: 'Bangkok, Thailand',
            desc: 'Multithread Labs is a B.O.I registered web agency. Most of the projects that I\'m currently involved with are done with this company.',
            responsibilities: [
                'Project Development Manager',
                'Senior Developer',
                'Q & A',
            ],
            achievements: [
                'Solidified multiple partners and clients',
                'Successfully took over prior high profiled clients and still do consulting',
                'Personally improved speed and efficiency of my clients website by 10X (LMC Auto)'
            ],
            skills: [
                'stakeholder-interaction',
                'client-interaction',
                'project-management',
            ],
            projects: [
                {
                    date: '11/2020 - 01/2024',
                    site: '<a href="http://eezze.io" class="site-link" target="_blank">Eezze.io</a>',
                    role: 'Project Manager & Senior Architect & Senior Backend Typescript',
                    location: 'Bangkok, Thailand',
                    desc: 'For the past three years, my team and I have dedicated ourselves to a project called Eezze. It\'s a versatile cross-platform framework that simplifies development across major areas like REST, Websockets, and Cron. This framework seamlessly integrates with an AI-powered web UI, functioning as a low-code/no-code solution. Moreover, it provides a suite of tools to automate and integrate various aspects of the software development lifecycle, constantly expanding its capabilities. Our platform boasts a human-curated template store, complemented by AI intelligence, allowing for the creation of projects through simple prompts while retaining full customization options.',
                    type: 'Internal Project',
                    responsibilities: [
                        'Conceptualize and implement a cross platform Typescript framework. This framework has to seamlessly work on servers and various cloud vendors',
                        'Full Stack Developer (Vue, Node, redis, ethers.js, bash, Cli tool interfaces, docker, flutter, figma plugin)',
                        'Create a transpiler from a QML like language to flutter (written in Node)',
                        'Create a robust UI to interface with our Framework',
                    ],
                    achievements: [
                        'Created a finished v.1 framework',
                        'Created a v.1 QML (like language) to flutter transpiler',
                        'Fully functioning UI interface',
                    ],
                    skills: [
                        'project-management',
                        'q-a-a',
                        'node-js',
                        'express-js',
                        'typescript',
                        'javascript',
                        'mysql',
                        'big-data',
                        'bash',
                        'docker',
                        'ansible',
                        'aws',
                        'gcp',
                        'azure',
                        'git',
                        'css',
                        'html',
                        'less',
                        'css',
                        'vite',
                        'vue-js',
                        'nuxt',
                        'ant-design',
                        'flutter',
                        'ats',
                        'transpiler',
                        'web-scraping',
                        'internationalization',
                        'vagrant',
                    ],
                },
                {
                    date: '11/2021 - 07/2022',
                    site: '<a href="http://yeild.app" class="site-link" target="_blank">Yield.app</a>',
                    role: 'Senior backend node & Feature Architect',
                    location: 'Bangkok, Thailand',
                    type: 'Full Time Consultant (On Site)',
                    desc: 'This initiative involved a yield farming project where I served as a full-time consultant and senior backend developer. My responsibilities encompassed conceptualizing and implementing new features while enhancing the existing functionalities. Additionally, I designed various tools aimed at automating internal processes, contributing significantly to establishing a more robust system in preparation for the v2 launch. Unfortunately this position came to an end due to a near fatal motorbike accident that I had.',
                    responsibilities: [
                        'Designing, Maintaining and Conceptualizing new features',
                        'Full Stack Developer',
                        'Designing tools for better automation',
                    ],
                    achievements: [
                        'Created a tool on my own initiative on holiday that ended up saving the company 100\s of hours of work and helped them better manage a billon dollars of assets',
                        'Created a tool that enabled the company to find over 30 critical bugs just before v.2 launch',
                    ],
                    skills: [
                        'stakeholder-interaction',
                        'q-a-a',
                        'node-js',
                        'express-js',
                        'typescript',
                        'javascript',
                        'mysql',
                        'bash',
                        'docker',
                        'redis',
                        'react-web',
                        'html',
                        'css',
                        'ethers-js',
                        'tui',
                        'data-aggregation',
                        'internationalization',
                        'git',
                    ],
                },
                {
                    date: 'Early 2020 - 01/2021',
                    site: '<a href="http://sevenpeakssoftware.com" class="site-link" target="_blank">Seven Peaks Software</a>',
                    role: 'Project Manager & Fullstack Developer',
                    type: 'Full Time Contract (On Site)',
                    location: 'Bangkok, Thailand',
                    desc: 'At Seven Peaks Software, a top web agency in Thailand, I joined just after the initial COVID lockdowns hit Thailand. I was one of three project managers, handling everything from gathering customer needs to resolving issues between clients and the development team. I worked with some big names like CPP Group, Banana I.T, and ERX Crypto Exchange. Sometimes, I even pitched in as a developer because of my coding background. But then, I left to start my own thing—my current project, Eezze.io.',
                    type: 'Full Time',
                    responsibilities: [
                        'Project Manager',
                        'SCRUM Master',
                        'Full Stack Developer (Node, C#)',
                    ],
                    achievements: [
                        'Successfully finished ERX crypto exchange',
                        'Under my leadership and collaboration with the internal team we won contracts with CPP Group (Thailand\'s biggest oil company)',
                        'I created an internal automation tool which helped us automate the initialization of all the documentation and onboarding process of any new project that came into the company',
                    ],
                    notableClients: [
                        'CPP Group',
                        'Banana I.T',
                        'ERX Trading Platform',
                    ],
                    skills: [
                        'project-management',
                        'client-interaction',
                        'stakeholder-interaction',
                        'scrum-master',
                        'documentation',
                        'q-a-a',
                        'mentoring',
                        'git',
                        'client-interaction',
                        'node-js',
                        'typescript',
                        'javascript',
                        'g-apis',
                        'firebase',
                        'mysql',
                        'vue-js',
                        'html',
                        'css',
                        'c-s',
                        'internationalization',
                    ],
                },
                {
                    date: '2019 - 2020 (Shelved due to covid)',
                    site: '<a href="http://kindi.menu" class="site-link" target="_blank">Kindi.menu</a>',
                    role: 'Co Founder & Senior Systems Architect',
                    type: 'Internal Project',
                    location: 'Bangkok, Thailand',
                    desc: 'This project entails the development of a modular QR-based digital menu tailored for restaurants and bars. The Minimum Viable Product (MVP) comprises a multilingual digital menu accessible to patrons through a QR code placed on their table. Presently, this initiative remains shelved as the covid situation made this project dormant',
                    responsibilities: [
                        'Project Development Manager',
                        'Full Stack Developer',
                    ],
                    achievements: [
                        'Successfully pitched project to investors resulting in seed round investment',
                        'Attracted multiple partners that were waiting for our alpha launch before until covid'
                    ],
                    skills: [
                        'node-js',
                        'typescript',
                        'javascript',
                        'dynamo-db',
                        'vue-js',
                        'ant-design',
                        'sass',
                        'pwa',
                        'git',
                        'big-data',
                        'internationalization',
                    ],
                },
                {
                    date: '05/2019 - 06/2019',
                    site: 'LMC Automotive Mobile App Prototype',
                    role: 'Solution Architect & Senior Developer',
                    location: 'Bangkok, Thailand',
                    type: 'Consultation / Client Project',
                    desc: 'Due to the lack of Qlik technology compatibility with mobile platforms within the allocated prototype budget, I was rehired to conceptualize and build a native/webview/Qlik hybrid. This solution played a pivotal role in securing the company\'s A-round investment, enabling them to progress further with their product development.',
                    responsibilities: [
                        'Coordinate with Outsourcify front end team to create a mobile UI that would function like an app',
                    ],
                    achievements: [ 
                        'Successfully create a prototype application',
                        'Created bridged two technologies to share sessions for seamless integration with the mobile website',
                    ],
                    skills: [
                        'q-a-a',
                        'qlik',
                        'node-js',
                        'javascript',
                        'vue-js',
                        'react-native',
                        'git',
                        'internationalization',
                    ],
                },
                {
                    date: '05/2019 - 06/2019',
                    site: 'LMC Automotive API',
                    role: 'Solution Architect & Senior Developer',
                    location: 'Bangkok, Thailand',
                    type: 'Consultation / Client Project',
                    desc: 'Given the numerous uncertainties in the initial solution, the client identified specific areas of improvement within the API. I was subsequently engaged to design and develop the API, focusing on enhanced data caching and performance optimization, addressing the initial delays associated with loading Qlik APIs.',
                    responsibilities: [
                        'Coordinate with LMC internal staff to hire an in house dev team',
                        'Lead development & architect of their new API revamp',
                    ],
                    achievements: [ 
                        'Re-architected their API\'s to be more performant with more caching',
                    ],
                    skills: [
                        'q-a-a',
                        'qlik',
                        'mysql',
                        'php',
                        'node-js',
                        'javascript',
                        'vue-js',
                        'git',
                        'internationalization',
                    ],
                },
                {
                    date: '2019 - 2021 (Partner went bankrupt due to covid)',
                    site: '<a href="https://cannatrack-dev.multithreadlabs.io" class="site-link" target="_blank">GrowTrack.io</a>',
                    role: 'Senior Systems Architect & Senior developer',
                    type: 'partnership',
                    location: 'Bangkok, Thailand',
                    type: 'Client Project to Partner Project',
                    desc: 'This project involves an agricultural management system designed specifically to assist farms cultivating medicinal marijuana in maintaining legal compliance. The system meticulously monitors the plant\'s life cycle, substances employed, and overall quality. Presently, this initiative remains undisclosed as it is in the private alpha phase of development.',
                    responsibilities: [
                        'Project Development Manager',
                        'Senior Full Stack Developer',
                        'Q & A'
                    ],
                    achievements: [
                        'Successfully transformed a client into being a partner / investor, resulting in creating a multitenancy platform for agricultural based businesses',
                        'From my consultation the platform now has a 3 month road map and will become a much broader platform',
                    ],
                    skills: [
                        'stakeholder-interaction',
                        'php',
                        'mysql',
                        'laravel',
                        'html',
                        'css',
                        'javascript',
                        'vue-js',
                        'ant-design',
                        'git',
                        'pwa',
                        'react-native',
                    ],
                },
                {
                    date: '2018 - 2020 (Due to the crypto bear market this project got shelved)',
                    site: '<a href="http://populi.one" class="site-link" target="_blank">Populi.one</a>',
                    role: 'Co Founder & Senior Systems architect & Senior Dev',
                    location: 'Bangkok, Thailand',
                    desc: 'Populi is a protocol-driven technology stack facilitating simultaneous trade tracking and execution across more than 100 cryptocurrency exchanges.',
                    responsibilities: [
                        'Project Development Manager',
                        'Full Stack & Mobile Developer & Protocol Architect',
                    ],
                    achievements: [
                        'Went on multiple road shows',
                        'Solidified major partners in the Crypto & Blockchain space',
                        'Personally designed and implemented a custom security protocol',
                        'Personally solidified seed investment',
                    ],
                    skills: [
                        'node-js',
                        'typescript',
                        'javascript',
                        'aws',
                        'cryptography',
                        'mysql',
                        'react-native',
                        'electron',
                        'vue-js',
                        'html',
                        'css',
                        'sass',
                        'ant-design',
                        'git',
                        'nuxt',
                        'fintech',
                        'web-scraping',
                        'data-aggregation',
                    ],
                },
            ],
        },
        {
            date: '02/2018 - 01/2019',
            site: '<a class="job-title" href="http://ypbsystems.com" class="site-link" target="_blank">YPBSystems.com</a>',
            role: 'Head of I.T and Senior developer',
            location: 'Bangkok, Thailand',
            desc: 'YPB Systems is an anti-counterfeit company offering a platform for businesses to conduct consumer campaigns aimed at data generation. This data undergoes processing and can be accessed through various report formats via a comprehensive dashboard.',
            responsibilities: [
                'Head of I.T',
                'Senior Developer',
            ],
            notableClients: [
                'Unilever',
                'Central Bank of Pakistan',
            ],
            achievements: [
                'Optimized their platform',
                'Designed and developed a QR code generator that was capable of generating 100\'s times faster than what they currently had',
                'Did prototypes for high profiling clients such as The State Bank of Pakistan & Unilever',
                'Saved them over a million baht on outsourcing work by personally doing it in house',
            ],
            skills: [
                'node-js',
                'typescript',
                'javascript',
                'mysql',
                'aws',
                'php',
                'html',
                'css',
                'vue-js',
                'qt',
                'git',
                'cpp',
                'ocr',
            ],
        },
        {
            date: '2017 - present',
            site: '<a href="http://trademerch.io" class="site-link" target="_blank">Trademerch.io</a>',
            role: 'Co Founder & Senior Systems architect',
            type: 'personal',
            location: 'Bangkok, Thailand',
            desc: 'Trademerch is a trademark monitoring service intended for individuals seeking protection against trademark infringement. This service interfaces with the USPTO APIs to detect and alert clients about potential trademark violations.',
            responsibilities: [
                'Backend Developer & AWS Services Integration Infrastructure Architect',
            ],
            achievements: [
                'Partnered up with 2 companies and took a prototype to a project that\'s very close to getting major investment',
                'Retained 95% of our customer base on the prototype website with a glowing reference from our current customers for over 7 years',
                'From my consultation the project took a lager scale and is currently moving to AWS cloud services and serverless infrastructure'
            ],
            skills: [
                'client-interaction',
                'bash',
                'node-js',
                'typescript',
                'javascript',
                'mysql',
                'elasticsearch',
                'big-data',
                'aws',
                'php',
                'git',
                'wordpress',
                'react-native',
                'chrome-extension',
                'xml',
                'html',
                'css',
                'vue-js',
            ],
        },
        {
            date: '11/2017 - 02/2018',
            site: '<a href="http://my-webspot.com" class="site-link" target="_blank">My-Webspot.com</a>',
            role: 'Project manager, systems architect, senior developer and senior team technology trainer)',
            location: 'Bangkok, Thailand',
            desc: 'This web agency offers a spectrum of services and incubates various startups. I led the design and management of a team tasked with developing a website for one of their new projects.',
            responsibilities: [
                'Project Development Manager',
                'Senior Full Stack Developer',
                'Senior Trainer',
            ],
            achievements: [
                'Optimized multiple internal and external processes and centralized everything into one platform',
                'Trained multiple junior staff',
                'Saved the company over a million baht in one day at an Expose in france'
            ],
            skills: [
                'project-management',
                'mentoring',
                'scrum-master',
                'node-js',
                'mysql',
                'symfony',
                'javascript',
                'php',
                'git',
                'html',
                'css',
                'vue-js',
            ],
        },
        {
            date: '05/2016 - 10/2017',
            site: '<a href="http://outsourcify.net" class="site-link" target="_blank">Outsourcify LTD</a>',
            role: 'Senior programmer, systems architect and team leader',
            location: 'Bangkok, Thailand',
            desc: 'At this web agency, we successfully delivered projects for prominent clients like Toyota, LMC Automotive, and numerous other high-profile entities. My role extended beyond conventional project deliver, I was entrusted with mastering and executing projects in cutting-edge technologies, often navigating uncharted territory where expertise was scarce at project initiation. Moreover, I assumed the pivotal responsibility of being the company\'s representative during on-site visits to esteemed clients such as Toyota, assuming the role of team manager, ensuring seamless coordination and project success.',
            responsibilities: [
                'Project Development Manager (Project Base)',
                'Senior Developer',
            ],
            achievements: [
                'Solidified multiple clients',
                'Managed projects in a commercial environment for the first time',
                'I was the representative for our company at the Toyota site when we were working on the Siam STM Project for Toyota',
            ],
            notableClients: [
                'LMC Automotive',
                'Toyota, Thailand',
                'Secrets of Siam',
            ],
            skills: [
                'project-management',
                'stakeholder-interaction',
                'client-interaction',
            ],
            projects: [
                {
                    date: '08/2017 - 10/2017',
                    site: 'Secrets of Siam',
                    role: 'PM',
                    location: 'Bangkok, Thailand',
                    desc: 'As the lead and senior developer for the Toyota project, I served as the project manager during its initial stages, utilizing the project template as the foundation for subsequent projects. Our team delivered a substantial and resilient solution for a prominent local travel agency, contributing to its growth as one of Thailand\'s top agencies.',
                    responsibilities: [
                        'Project Management',
                        'Coordinate with the fe & be development teams',
                    ],
                    achievements: [
                        'Successfully coordinated reuse of previous project templates',
                        'Mentored new a newly created dev team on project template',
                    ],
                    skills: [
                        'project-management',
                        'mentoring',	
                        'javascript',
                        'php',
                        'symfony',
                        'vue-js',
                    ],
                },
                {
                    date: '02/2017 - 10/2017',
                    site: 'LMC Automotive',
                    role: 'PM & Senior Developer',
                    location: 'Bangkok, Thailand',
                    desc: 'I successfully proposed and secured a contract by presenting a solution to the client alongside the company director. Subsequently, we collaborated closely with Qlik customer support and engaged a recommended expert to develop a unique integration with their APIs using a PHP/VueJS hybrid. The project resulted in the creation of a hyper performant financial forecasting tool tailored for the automotive industry.',
                    responsibilities: [
                        'Project Management',
                        'Update stakeholders and management daily',
                        'Worked with Qlik support and recommended third party expert',
                        'Coordinate with the front end team',
                        'Coordinate with the design team',
                        'Developed all back and front end business logic',
                    ],
                    achievements: [ 'Learnt the Qlik API\'s' ],
                    skills: [
                        'q-a-a',
                        'mysql',
                        'php',
                        'qlik',
                        'node-js',
                        'javascript',
                        'vue-js',
                        'git',
                        'internationalization',
                    ],
                },
                {
                    date: '09/2016 - 02/2017',
                    site: 'Siam Toyota',
                    role: 'Full Stack Symfony Developer',
                    location: 'Bangkok, Thailand',
                    desc: '<p>This project, a new intranet with library management, department blog, forum, and events features, posed significant challenges including scope changes and communication issues. Managing complex workflows for a large facility in Bangna, Bangkok, required implementing intricate role management and hierarchies.</p><p>I navigated through unfamiliar technologies like Symfony, VueJS, and a specialized UI builder for blogs, making this project a continuous learning experience. Balancing high expectations from both the client and company management, I also led and mentored the team, addressing challenges efficiently.</p>',
                    responsibilities: [
                        'Project Management',
                        'Lead on site team meetings with the client',
                        'Lead work shops and on site training once the project was completed',
                        'Managed a team of interns who were doing other parts of the documentation',
                        'Reviewed all the documentation before submitting to the clients',
                        'Conducted and contributed to the functional spec',
                        'Senior Developer and managed a team of devs to build the solution',
                        'Forked and customized the symfony scaffold CLI tool to generate custom pages for this project',
                    ],
                    achievements: [
                        'Learnt Symfony to do the project',
                        'Learnt VueJS',
                    ],
                    skills: [
                        'q-a-a',
                        'azure',
                        'sso',
                        'mysql',
                        'cli',
                        'node-js',
                        'javascript',
                        'git',
                    ],
                },
                {
                    date: '08/2016 - 09/2016',
                    site: 'Internal Code Generator',
                    role: 'Node JS Developer',
                    location: 'Bangkok, Thailand',
                    isConfidential: true,
                    desc: 'While employed at the company, I contributed to an ongoing project for a client. The existing codebase exhibited repetitive patterns, given the nature of the client\'s product outputs for customers. Consequently, I was tasked with developing a Node-based Command-Line Interface (CLI) tool with a Terminal UI to enhance and optimize the efficiency of this process.',
                    responsibilities: [
                        'Created a process which saved weeks of development over a period of time',
                    ],
                    achievements: [
                        'Learnt more about code templating and code parsing',
                        'Reduced development time therefor reducing cost and maximizing profits',
                    ],
                    skills: [
                        'cli',
                        'q-a-a',
                        'node-js',
                        'javascript',
                        'git',
                        'cli',
                    ],
                },
                {
                    date: '07/2016 - 08/2016',
                    site: 'Client Website App',
                    role: 'Angular Developer',
                    location: 'Bangkok, Thailand',
                    isConfidential: true,
                    desc: 'In this project, my role involved providing support to address the finalization of various components on the website, collaborating closely with the team at the time. Additionally, I assumed responsibility for specific sections of the site, ensuring alignment with our project timeline.',
                    responsibilities: [
                        'Create a few pages of an already ongoing project with another team',
                    ],
                    achievements: [
                        'Learnt Angular JS for my small part of this project'
                    ],
                    skills: [
                        'q-a-a',
                        'node-js',
                        'angular',
                        'javascript',
                        'css',
                        'html',
                        'git',
                    ],
                },
                {
                    date: '05/2016 - 07/2016',
                    site: 'Client Mobile App',
                    role: 'React Native Developer',
                    location: 'Bangkok, Thailand',
                    isConfidential: true,
                    desc: 'Initially hired for my expertise in cross-platform mobile development, I navigated the challenges of learning and coding simultaneously. React Native\'s early-stage instability and scarce learning resources added complexity. Despite these hurdles, the project was successfully delivered for the client, securing my continued employment with the company.',
                    responsibilities: [
                        'Architect & Develop the solution',
                        'Update stakeholders on a weekly basis',
                    ],
                    achievements: [
                        'Learn React Native',
                        'Learn Firebase',
                        'Learnt React Native with very little resources',
                        'Transitioned from temporary contract to permanent position',
                    ],
                    skills: [
                        'q-a-a',
                        'node-js',
                        'firebase',
                        'javascript',
                        'react-native',
                        'git',
                        'internationalization',
                    ],
                },
            ]
        },
        {
            date: '01/2015 - 10/2015',
            site: '<a href="https://Ebuyer.co.uk" class="site-link" target="_blank">Ebuyer LTD</a>',
            role: 'Full Stack Developer',
            location: 'Goole, Uk',
            desc: 'At Ebuyer, a leading hardware distributor in the UK, I contributed significantly as part of the development team accountable for their pivotal ECommerce platform. My role involved integral contributions to its development and enhancement, ensuring a robust and effective online platform for the company\'s operations.',
            responsibilities: [
                'Full Stack Developer',
                'Q & A',
            ],
            achievements: [
                'Got my first commercial job that wasn\'t a start up',
                'I became the representative for the I.T department of over 50 people',
                'Became the department intermediary for QFD between departments due to my industrial experience as a youngster',
            ],
            skills: [
                'mysql',
                'node-js',
                'mysql',
                'php',
                'html',
                'css',
                'javascript',
                'vagrant',
                'bazaar',
            ],
        },
        {
            date: '2012 - 2014',
            site: '<a href="https://www.linkedin.com/company/crack-learning-ltd-/" class="site-link" target="_blank">HiWay Language Learning App</a>',
            role: 'Co Founder & Senior Dev',
            location: 'Xiamen, China',
            desc: 'HiWay App language learning platform',
            desc: 'Hiway represented a groundbreaking real-time chat application that seamlessly integrated various facets of language learning into a unified platform, setting a new standard in its era. The application\'s innovation lay in its multifaceted features, notably incorporating a real-time chat function complemented by integrated spaced repetition learning flashcards. Additionally, it boasted a community-driven dictionary, fostering collaborative learning experiences through user-generated content and community-driven learning materials. What set Hiway apart was its unique \'learn as you chat with minimal effort\' approach, streamlining language acquisition within everyday conversations."',
            responsibilities: [
                'Co CEO & Project Development Manager',
                'Senior Developer',
                'Android Developer',
            ],
            achievements: [
                'We achieved a user base of 40k users',
                'Me and my partner also was featured in multiple blogs and news papers in China',
                'We also hosted multiple events over the space of a year'
            ],
            skills: [
                'cli',
                'c',
                'cpp',
                'bash',
                'node-js',
                'mysql',
                'php',
                'mysql',
                'code-igniter',
                'web-scraping',
                'html',
                'css',
                'qt',
                'java',
                'native-android',
                'big-data',
                'internationalization',
                'web-scraping',
                'svn',
                'data-aggregation',
            ],
        },
    ],

    skills: [
        'Desktop and Web application development with; C / C++, Developing with Qt Creator, Qml, PHP, Laravel, Symfony, Composer, Angular JS, Vue Js, Node Js, Electron (Desktop apps with html and css), MySQL, CSS, HTML, CSS, Java and Wordpress',
        'Mobile cross platform development with React Native, Apache Cordova, V-Play and Qml',
        'Firebase NoSql database, Qlik Api’s and SQL',
        'Git, SVN and Bazaar Version Control',
    ],

    intro: [
        'From a young age, I exhibited a keen interest and natural talent for computers, engaging in self-directed programming and quickly grasping new concepts from the age of 11.',

        'Through extensive involvement with startups, I\'ve gained a profound understanding of diverse roles. This has equipped me to take on various responsibilities as required, ensuring adaptability and proficiency in tasks across different domains.',

        'In corporate settings like Ebuyer & Outsourcify, I\'ve recognized the significance of maintaining a proactive, solution-oriented mindset. This not only enhances task efficiency but also fuels my commitment to continuous learning and improvement.',

        'With these skills and my proficiency in multiple languages, I am confident in providing substantial value to any team. As a highly motivated and adaptable individual, I am poised to contribute effectively to any project or organization seeking these qualities.',

        'For more information, please visit my detailed personal statement <a href="https://ryansresume.s3.amazonaws.com/personal-statement.html" target="_blank">here</a>',
    ],

    currentlyDoing: [
        '<a href="http://Trademerch.io" target="_blank">Trademerch.io (Maintenance)</a>',
        'Relocated to the U.K and Open to new opportunities',
    ],

    languages: [
        'English (Fluent)',
        'Thai (Fluent)',
        'Mandarin Chinese (Conversational)',
        'Loa (Basic - Intermediate)',
    ],

    references: [
        {
            name: 'Rolf Streefkerk',
            role: 'Senior Cloud Architect',
            company: 'Multithread Labs',
            location: 'Bangkok, Thailand',
            email: 'rolf@multithread.io',
            linkedIn: 'https://www.linkedin.com/in/rolfstreefkerk/',
            // phoneNo: '+61-481-159-231'
            hasLinedInRef: true,
        },
        {
            name: 'Greg O’Shea',
            role: 'COO',
            company: 'YPB Systems',
            location: 'Bangkok, Thailand',
            email: 'gosha001@hotmail.com',
            linkedIn: 'https://www.linkedin.com/in/greg-o-shea-b4974a7/',
            // phoneNo: '+61-481-159-231'
            hasLinedInRef: true,
        },
        {
            name: 'Gareth Nellis',
            role: 'Ex CEO',
            company: 'Multithread Labs',
            location: 'Bangkok, Thailand',
            email: 'garethnellies@gmail.com',
            // phoneNo: '+66-96-927-9410'
            hasLinedInRef: true,
        },
        {
            name: 'Daniel Mathieu',
            role: 'Co CEO',
            company: 'Lie Hun Ltd',
            location: 'Xiamen, China',
            email: 'dmathieuva@gmail.com',
            linkedIn: 'https://www.linkedin.com/in/coder-dan/',
            website: 'https://coderdan.dev/',
            // phoneNo: '+86-1-885-923-6706'
            hasLinedInRef: false,
        },
        {
            name: 'Benoit Schneider',
            role: 'Managing Technical Director',
            company: 'Outsourcify Ltd.',
            location: 'Bangkok, Thailand',
            email: 'benoit@outsourcify.net',
            linkedIn: 'https://www.linkedin.com/in/benoitschneider/',
            // phoneNo: '+66-844-413-639'
            hasLinedInRef: true,
        },
        {
            name: 'Cyrus Salimian',
            role: 'I.T Team lead & Senior Recruiter',
            company: 'Parker Bridge Recruitment.',
            location: 'Bangkok, Thailand',
            email: 'csalimian@argyllscott.co.th',
            linkedIn: 'https://www.linkedin.com/in/cyrussalimian/',
            // phoneNo: '+66-615-646-519'
            hasLinedInRef: true,
        },
        {
            name: 'Leif Åsmund Mørk',
            role: 'CTO',
            company: 'Seven Peaks Software',
            location: 'Bangkok, Thailand',
            contactWithLi: true,
            linkedIn: 'https://www.linkedin.com/in/leifasmundmork/',
            email: 'http://www.linkedin.com/in/leifasmundmork',
            // phoneNo: '+66-656-893-795'
            hasLinedInRef: true,
        },
        {
            name: 'Tom Heath',
            role: 'Head of HR',
            company: 'Yield.app',
            location: 'Bangkok, Thailand',
            email: 'tom@yield.app',
            linkedIn: 'https://www.linkedin.com/in/theath1/',
            // phoneNo: '+66-952-530-103'
            hasLinedInRef: true,
        },
        {
            name: 'Dylan Clarkson',
            role: 'Head of Marketing for SEA and Australia',
            company: 'Toyota',
            location: 'Bangkok, Thailand',
            email: 'dylan.clarkson@yahoo.com',
            linkedIn: 'https://www.linkedin.com/in/dylan-clarkson-07814839/',
            // phoneNo: '+66-955-017-374'
            hasLinedInRef: true,
        },
    ],
}